################################################################################
#
# * This file is part of SplashSync Project.
# *
# * Copyright (C) Splash Sync <www.splashsync.com>
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# *
# * For the full copyright and license information, please view the LICENSE
# * file that was distributed with this source code.
# *
# * @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Include Pipeline Templates
include:
  - remote: 'https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/gitlab/php/defaults.yaml'
  - remote: 'https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/gitlab/pages.yaml'
  - remote: 'https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/gitlab/manifest.yaml'

################################################################
# Quality Tests
################################################################

quality:php-8.2:
    extends: .quality
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2

quality:php-8.1:
    extends: .quality
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1

################################################################
# Functional Tests
################################################################

.functional-soap:
    extends:    .functional
    ################################################################################
    # Run Test Script
    script:
        # Install Symfony CLI
        - wall-e add:symfony
        # Start Web Server
        - symfony serve -d
        # Execute PhpUnit Tests
        - vendor/bin/phpunit --log-junit $CI_PROJECT_DIR/full-report.xml

functional:php-8.2:
    extends: .functional-soap
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2

functional:php-8.1:
    extends: .functional-soap
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1

#
#################################################################
## Set any variables we need
#variables:
#  COMPOSER_MEMORY_LIMIT:  -1
#  SYMFONY_DEPRECATIONS_HELPER:  disabled
#
#################################################################
## Defined Pipeline Stages
#stages:
#  - quality
#  - functional
#  - deploy
#
#################################################################
## Base Tests
#################################################################
#
#.base:    &base
#    tags:
#        - Dedicated
#    artifacts:
#        when: always
#        reports:
#            junit: "$CI_PROJECT_DIR/*-report.xml"
#    ################################################################################
#    # Install & Configure Environnement
#    before_script:
#      # Install Symfony
#      - composer update
#      # Install Symfony CLI
#      - wall-e add:symfony
#    ################################################################################
#    # Run After Script
#    after_script:
#      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh
#
#################################################################
## Quality Tests
#################################################################
#
#.quality:    &quality
#    <<:         *base
#    stage:      quality
#    ################################################################################
#    # Run Test Script
#    script:
#      # Execute Grumphp Testsuite
#      - wall-e grumphp:quality
#      - wall-e grumphp:stan
#
#quality:php-8.1:
#  image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
#  <<: *quality
#
#quality:php-8.0:
#  image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
#  <<: *quality
#
#################################################################
## Functional Tests
#################################################################
#
#.functional:    &functional
#    <<:         *base
#    stage:      functional
#    ################################################################################
#    # Run Test Script
#    script:
#        # Start Web Server
#        - symfony serve -d
#        # Execute PhpUnit Tests
#        - vendor/bin/phpunit --log-junit $CI_PROJECT_DIR/full-report.xml
#
#functional:php-8.1:
#    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
#    <<: *functional
#
#functional:php-8.0:
#    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
#    <<: *functional

##################################################################
### Build Documentation
##################################################################
#pages:
#    image:    registry.gitlab.com/splashsync/php-console:pages
#    stage:    deploy
#    tags:
#      - Dedicated
#    services:
#      - docker:dind
#    ################################################################################
#    # Run Test Script
#    script:
#      # Run Composer to Build deps
#      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
#      # Build Documentation
#      - php vendor/bin/grumphp run --tasks=build-docs
#    artifacts:
#        paths:
#            - public
