################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

name: splash_soap_bundle

services:

    ################################################################################
    # PHP 8.3
    php-8.3:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3
        container_name: php-8.3.soap-bundle.local
        volumes:
            - ./:/var/www/html
            - php83-var:/var/www/html/var
            - php83-vendor:/var/www/html/vendor

    ################################################################################
    # PHP 8.2
    php-8.2:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
        container_name: php-8.2.soap-bundle.local
        volumes:
            - ./:/var/www/html
            - php82-var:/var/www/html/var
            - php82-vendor:/var/www/html/vendor

    ################################################################################
    # PHP 8.1
    php-8.1:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
        container_name: php-8.1.soap-bundle.local
        volumes:
            - ./:/var/www/html
            - php81-var:/var/www/html/var
            - php81-vendor:/var/www/html/vendor

networks:
    ################################################################################
    # Default Private Network    
    soap:
        driver: bridge
        ipam:
            config:
                - subnet: 172.116.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true

volumes:
    php83-var: ~
    php83-vendor: ~
    php82-var: ~
    php82-vendor: ~
    php81-var: ~
    php81-vendor: ~