services:
    ################################################################################
    # SPLASH SOAP Connector 
    splash.connectors.soap:
        class: Splash\Connectors\Soap\Services\SoapConnector
        arguments:  [ "@event_dispatcher", "@logger" ]
        tags:       
            # Register Soap Connector Actions
            - { name: "splash.connector"}
        
            